version: '3'
services:
  mysql:
    image: mysql:5.7
    # NOTE: Uncomment if you want to run the code of sqlboiler
    # volumes:
      # - ./docker/mysql/sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
