version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
