// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Departments", testDepartmentsUpsert)

	t.Run("DeptEmps", testDeptEmpsUpsert)

	t.Run("DeptManagers", testDeptManagersUpsert)

	t.Run("Employees", testEmployeesUpsert)

	t.Run("Salaries", testSalariesUpsert)

	t.Run("Titles", testTitlesUpsert)
}
