// Code generated by ent, DO NOT EDIT.

package department

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the department type in the database.
	Label = "department"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeptName holds the string denoting the dept_name field in the database.
	FieldDeptName = "dept_name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeDeptManager holds the string denoting the dept_manager edge name in mutations.
	EdgeDeptManager = "dept_manager"
	// Table holds the table name of the department in the database.
	Table = "departments"
	// DeptManagerTable is the table that holds the dept_manager relation/edge.
	DeptManagerTable = "dept_managers"
	// DeptManagerInverseTable is the table name for the DeptManager entity.
	// It exists in this package in order to avoid circular dependency with the "deptmanager" package.
	DeptManagerInverseTable = "dept_managers"
	// DeptManagerColumn is the table column denoting the dept_manager relation/edge.
	DeptManagerColumn = "department_dept_manager"
)

// Columns holds all SQL columns for department fields.
var Columns = []string{
	FieldID,
	FieldDeptName,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Department queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeptName orders the results by the dept_name field.
func ByDeptName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeptName, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeptManagerCount orders the results by dept_manager count.
func ByDeptManagerCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDeptManagerStep(), opts...)
	}
}

// ByDeptManager orders the results by dept_manager terms.
func ByDeptManager(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeptManagerStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDeptManagerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeptManagerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DeptManagerTable, DeptManagerColumn),
	)
}
