// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// DeptManager is the predicate function for deptmanager builders.
type DeptManager func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)
